### ISSUE TITLE
Doc for snapcraft's grade property missing

### ISSUE THREAD

**Issue by lool** [CanonicalLtd/ubuntu-core-docs#1]
grade: devel or stable was added end of August to:
https://github.com/snapcore/snapcraft/blob/master/schema/snapcraft.yaml
and is part of default snapcraft.yaml generated by snapcraft init, but is missing from the snapcraft syntax doc:
http://snapcraft.io/docs/build-snaps/syntax

**Comment by dholbach** [comment]
Pulling from snapcraft master will fix it.

**Comment by caldav** [comment]
Fixed some time ago on snapcraft.io (https://github.com/CanonicalLtd/snappy-docs)
