### ISSUE TITLE
repo command in building steps does not work

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [CanonicalLtd/ubuntu-core-docs#14]
$ repo init -u <my_user>@github.com:CanonicalLtd/ubuntu-core-docs.git
or
$ repo init -u git@github.com:CanonicalLtd/ubuntu-core-docs.git

fail:

Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
Get git@github.com:CanonicalLtd/ubuntu-core-docs.git
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ repo init -u <my_user>@github.com:CanonicalLtd/ubuntu-core-docs.git

**Comment by jhodapp** [comment]
This fixes the issue: https://github.com/CanonicalLtd/ubuntu-core-docs/pull/15
