### ISSUE TITLE
Nav reorganization commit discussion

### ISSUE THREAD

**Issue by caldav** [CanonicalLtd/ubuntu-core-docs#18]
@jhodapp @morphis 

I mistakenly pushed a nav change to trunk, that I actually wanted to discuss with you beforehand: https://github.com/CanonicalLtd/ubuntu-core-docs/commit/82181d7a129f60e2d7cdfd5aa2428dfc3a958c11

> 
> * Move Go to Production at the end
> 
> Nav renames:
> * Ubuntu Core Stacks -> Build a stack
> * Stack Items -> Features
> 
> The main purpose of the rename is to provide a visible path from having an empty board to a device ready for production:
> Build a device -> Build a stack -> Go to production
> 
> By making "Build a stack" an action to enable features on the device, it give a better mental map of the entire process, and immediately puts the Ubuntu Core Stacks name in context when the user sees it as the title of the Introduction page.
> 

Does that work for you?

**Comment by jhodapp** [comment]
I like the action-oriented approach to these nav titles. I can't think of a better phrase/title for it, so I'm good with it!
