### ISSUE TITLE
docs.ubuntu.com contains Phone Documentation

### ISSUE THREAD

**Issue by knitzsche** [CanonicalLtd/ubuntu-core-docs#38]
But there is no Phone.

**Comment by caldav** [comment]
Hi Kyle, I think you have picked the wrong bug tracker for this discussion. Let's move here please https://github.com/canonical-websites/docs.ubuntu.com

**Comment by knitzsche** [comment]
Thanks David. I opened this https://github.com/canonical-websites/docs.ubuntu.com/issues/113
