### ISSUE TITLE
image building and extra snaps

### ISSUE THREAD

**Issue by knitzsche** [CanonicalLtd/ubuntu-core-docs#5]
This page [1] shows how to use the ubuntu-image --extra-snaps arg to install extra snaps in your image. This is fine for development, but for production I believe the proper way is to add a list the snaps in your model assertion ("registered snaps" key) and ensure they are published in the store associated with the current user. 

The reason: if you use --extra-snaps arg the device does not have the info about these extra snaps installed in case of a reset so it would not reset to a complete state. But, if those snaps are listed in the model assertion, the device in theory has the info needed to restore to the original state (same snaps installed).

[1] https://github.com/CanonicalLtd/ubuntu-core-docs/blob/master/en/guides/build-device/image-building.md

**Comment by caldav** [comment]
If you mean the "required-snaps" key, I agree, but note that the functionality is not working as expected yet (they should be impossible to remove). https://bugs.launchpad.net/snappy/+bug/1649837
